name: kindred_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_app_check: ^0.4.1
  firebase_ai: ^3.3.0
  flutter_riverpod: ^3.0.2
  google_sign_in: ^7.2.0
  firebase_analytics: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.2

flutter:
  uses-material-design: true
